#this docker-compose file lets us easily start up a postgres database
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432" #will run on port 5432
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod! #this environment variable as a password